### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [sanG-github/Search-Analytics#25]
Hello Sang 👋 , thank you for your effort on the code submission. I am Olivier from Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Please note that you don't have to close any of my created issues after merging your PRs, I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us right away so that we can plan accordingly.

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by olivierobert** [comment]
I have now completed the first round of reviews. Have a check on the opened issue and share your feedback with us.

Note that we keep the code review limited, and I opened only the most prominent issues to keep the review process short and efficient.

**Comment by sanG-github** [comment]
Nice to meet you @olivierobert,
Thank you so much for spending time reviewing my GitHub repo, I very much appreciate that. But because I only have the night time to implement the assignment, I cannot deliver my best effort for coding, testing and deploying.

And as you mentioned before, I don't have much free time, so can I extend the time to fix the issues and write more tests to ensure the code quality? I will try my best to improve and fix the issues. 

Thank you in advance, have a nice week!

**Comment by olivierobert** [comment]
Thank you for the feedback on all open issues and the fixes done so far. 

As explained above, we aim to keep the code review process short so let's end this phase now. You can still make further improvements if you would like, but we should move on to the next stage in the meantime :-)

**Comment by sanG-github** [comment]
@olivierobert 
In the last words, I would like to say thank you for taking the time to review my codes, and I love this interview process at your company too. As I mentioned before, I regret not having much time to fix all the open issues. 

Nice to meet you, hope that we can meet each other later.
Best regards.
