### ISSUE TITLE
[Feature] Rendering of the search result page

### ISSUE THREAD

**Issue by olivierobert** [sanG-github/Search-Analytics#26]
## Issue

The HTML code for the search page is rendered as-is on the results page:

![Screen Shot 2565-09-19 at 10 15 34](https://user-images.githubusercontent.com/696529/190944329-2a0867f1-4ced-418b-a60b-6f1eab7a19be.png)

## Expected

The store HTML is rendered on the page so that a user can verify visually the parsing was correct.

**Comment by sanG-github** [comment]
@olivierobert 

Yeah! That is a piece of good and valuable information for the user. I'll implement a preview along with that code that helps the user to double-check the results.
