### ISSUE TITLE
[Feature] Improve attachment#index controller

### ISSUE THREAD

**Issue by olivierobert** [sanG-github/Search-Analytics#27]
## Issue

https://github.com/sanG-github/Search-Analytics/blob/89710d2165747250783ce0a6ab062ffe98944755/app/controllers/attachments_controller.rb#L2-L11

The current implementation relies on raising exceptions for flow control, This is generally considered as an antipattern ([see this long document](http://c2.com/cgi-bin/wiki?DontUseExceptionsForFlowControl)). Exceptions are great to pass messages between objects but less so within the same object :-) 

In addition, the redirection to the root path is no keywords have been uploaded seems unnecessary. Viewing the list of keywords without any keywords should render a blank state, i.e., it should not be broken.

Eventually, The short delay `0.001` in `PushNotificationWorker` seems very hacky 🙃 

Overall, the code looks complex and brittle.

## Expected

Simplify and improve the implementation of `attachment#index` by allowing viewing the view for `attachment#index` even if there are no uploaded files yet.

**Comment by sanG-github** [comment]
> Eventually, The short delay 0.001 in PushNotificationWorker seems very hacky 🙃
Yeah, I think it's so tricky 👨‍🎨 The problem I encountered is the error message arrives at the site very quickly (before the redirect). And I think the below solution will solve this problem.

> Simplify and improve the implementation of attachment#index by allowing viewing the view for attachment#index even if there are no uploaded files yet.
That's a good idea and a normal way to implement a listing page too. I chose this way to reduce the time of implementing the view for the `attachment#index`. I will resolve it by adding a button to upload an attachment on the list attachments page.
