### ISSUE TITLE
[Question] Why not using a Stimulus controller for the CSV upload form?

### ISSUE THREAD

**Issue by olivierobert** [sanG-github/Search-Analytics#29]
## Issue

https://github.com/sanG-github/Search-Analytics/blob/main/app/javascript/homepages/listen_upload_file.js could be implemented vis Stimulus since Hotwire is used in the application. It would allow making it easier to bind event listeners directly using HTML directives:

```
<button class="..." id="upload_file" type="button"  data-action="click->formCSV#upload">Upload file</button>
```

**Comment by sanG-github** [comment]
@olivierobert 

This is the first time I have had an opportunity to work with Rails 7, and typically Stimulus. And I also heard about their powerful functionality but didn't use them before. I think I will research them deeply and try to replace all my native javascript. 

Many thanks for your suggestion!

**Comment by olivierobert** [comment]
Okay. Noted. It is not a blocker so take this as an improvement idea.
