### ISSUE TITLE
[Bug] The UI is not responsive

### ISSUE THREAD

**Issue by olivierobert** [sanG-github/Search-Analytics#30]
## Issue

Some of the built-in Tailwind CSS classes for making the page response have been used:

![Screen Shot 2565-09-19 at 10 38 53](https://user-images.githubusercontent.com/696529/190946005-4a5a5e01-5a74-4a40-9206-25fc6f028f64.png)

However, some of the UI screens are not usable on smaller screens, e.g., the list of attachments.

![image](https://user-images.githubusercontent.com/696529/190946101-8b73bb5b-7cb0-400e-b6ef-f2200787347d.png)

## Expected

The UI should be usable on small screen sizes. A. simple solution would be to have each element be 100% of the width and move them below one another.

**Comment by sanG-github** [comment]
You catch a good point! 👍 

The hamburger button doesn't have any items inside it -> So I'll remove it from the view.
And I will fix all the pages, and give them a responsive view.
