### ISSUE TITLE
[Chore] Low test coverage

### ISSUE THREAD

**Issue by olivierobert** [sanG-github/Search-Analytics#31]
## Issue

While he made some efforts to add a few unit tests for models and, oddly enough, for channels, the code coverage is too low. You also left behind the minitest directory (these could be deleted :-)).

## Expected

The critical path of the application should have unit tests:
- CSV upload (services)
- Google Search page scraping (services)

**Comment by sanG-github** [comment]
Closes by resolving these issues:
#38 
#39 
#40 
#43 
#44 
#45
