### ISSUE TITLE
[Question] Why creating Worker classes instead of using ActiveJob

### ISSUE THREAD

**Issue by olivierobert** [sanG-github/Search-Analytics#32]
## Issue

Sidekiq is correctly used to implement background jobs since all worker classes include `Sidekiq::Job`. However, Sidekiq can also be integrated with ActiveJob (see [the official docs](https://edgeguides.rubyonrails.org/active_job_basics.html#backends)). Is there any specific reasons not to have picked the latter integration?

**Comment by sanG-github** [comment]
There are no specific reasons when using `worker` and include `Sidekiq::Job` instead of `jobs`. This is just a convention when I work with the old project. When I worked on this assignment, I preferred using the convention that I was familiar with, due to the time limitations. That's my bad 🙆‍♂️

**Comment by olivierobert** [comment]
No concerns. It actually makes sense to use Sidekiq Worker directly (see: https://andycroll.com/ruby/use-sidekiq-directly-not-through-active-job/) so I was more curious if you faced any issue and opted to use them instead.
